FROM golang:1.14-alpine AS build

WORKDIR /src/

COPY project/go.mod /src/
COPY project/go.sum /src/
RUN go mod download

COPY project/pokmonapi /src/pokmonapi
COPY project/gameserver/server.go /src/
RUN CGO_ENABLED=0 go build -o /bin/server

FROM scratch
COPY --from=build /bin/server /bin/server
ENTRYPOINT ["/bin/server"]
