FROM golang:1.14-alpine AS build

WORKDIR /src/

COPY project/go.mod /src/
COPY project/go.sum /src/
RUN go mod download

COPY project/gameapi /src/gameapi
COPY project/gameserver/game.go /src/
RUN CGO_ENABLED=0 go build -o /bin/game

FROM scratch
COPY --from=build /bin/game /bin/game
ENTRYPOINT ["/bin/game"]
