// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pokmonapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PokmonInfoClient is the client API for PokmonInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PokmonInfoClient interface {
	GetMonsterInfo(ctx context.Context, in *MonsterName, opts ...grpc.CallOption) (*MonsterNames, error)
	SetMonsterInfo(ctx context.Context, in *UserAndName, opts ...grpc.CallOption) (*Status, error)
	MonsterAttack(ctx context.Context, in *MonsterAction, opts ...grpc.CallOption) (*Status, error)
	JoinQueue(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*Status, error)
	//rpc LeaveQueue (UserName) returns (Status) {}                     // user wants to leave the queue because they scared
	LeaveGame(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*Status, error)
	SetUserName(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*Status, error)
	//rpc SetCredentials (Credentials) returns (Status) {}              // user sets Credentials to server *(this is extra)* //uncomment credentials lne 47
	GetHealthPoints(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthPoints, error)
	GetGameInfo(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*GameStatus, error)
	GetOpponentInfo(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*OpponentStatus, error)
}

type pokmonInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewPokmonInfoClient(cc grpc.ClientConnInterface) PokmonInfoClient {
	return &pokmonInfoClient{cc}
}

func (c *pokmonInfoClient) GetMonsterInfo(ctx context.Context, in *MonsterName, opts ...grpc.CallOption) (*MonsterNames, error) {
	out := new(MonsterNames)
	err := c.cc.Invoke(ctx, "/pokmonapi.PokmonInfo/GetMonsterInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokmonInfoClient) SetMonsterInfo(ctx context.Context, in *UserAndName, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/pokmonapi.PokmonInfo/SetMonsterInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokmonInfoClient) MonsterAttack(ctx context.Context, in *MonsterAction, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/pokmonapi.PokmonInfo/MonsterAttack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokmonInfoClient) JoinQueue(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/pokmonapi.PokmonInfo/JoinQueue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokmonInfoClient) LeaveGame(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/pokmonapi.PokmonInfo/LeaveGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokmonInfoClient) SetUserName(ctx context.Context, in *UserName, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/pokmonapi.PokmonInfo/SetUserName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokmonInfoClient) GetHealthPoints(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthPoints, error) {
	out := new(HealthPoints)
	err := c.cc.Invoke(ctx, "/pokmonapi.PokmonInfo/GetHealthPoints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokmonInfoClient) GetGameInfo(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*GameStatus, error) {
	out := new(GameStatus)
	err := c.cc.Invoke(ctx, "/pokmonapi.PokmonInfo/GetGameInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokmonInfoClient) GetOpponentInfo(ctx context.Context, in *RequestInfo, opts ...grpc.CallOption) (*OpponentStatus, error) {
	out := new(OpponentStatus)
	err := c.cc.Invoke(ctx, "/pokmonapi.PokmonInfo/GetOpponentInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PokmonInfoServer is the server API for PokmonInfo service.
// All implementations must embed UnimplementedPokmonInfoServer
// for forward compatibility
type PokmonInfoServer interface {
	GetMonsterInfo(context.Context, *MonsterName) (*MonsterNames, error)
	SetMonsterInfo(context.Context, *UserAndName) (*Status, error)
	MonsterAttack(context.Context, *MonsterAction) (*Status, error)
	JoinQueue(context.Context, *UserName) (*Status, error)
	//rpc LeaveQueue (UserName) returns (Status) {}                     // user wants to leave the queue because they scared
	LeaveGame(context.Context, *UserName) (*Status, error)
	SetUserName(context.Context, *UserName) (*Status, error)
	//rpc SetCredentials (Credentials) returns (Status) {}              // user sets Credentials to server *(this is extra)* //uncomment credentials lne 47
	GetHealthPoints(context.Context, *HealthRequest) (*HealthPoints, error)
	GetGameInfo(context.Context, *RequestInfo) (*GameStatus, error)
	GetOpponentInfo(context.Context, *RequestInfo) (*OpponentStatus, error)
	mustEmbedUnimplementedPokmonInfoServer()
}

// UnimplementedPokmonInfoServer must be embedded to have forward compatible implementations.
type UnimplementedPokmonInfoServer struct {
}

func (UnimplementedPokmonInfoServer) GetMonsterInfo(context.Context, *MonsterName) (*MonsterNames, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMonsterInfo not implemented")
}
func (UnimplementedPokmonInfoServer) SetMonsterInfo(context.Context, *UserAndName) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMonsterInfo not implemented")
}
func (UnimplementedPokmonInfoServer) MonsterAttack(context.Context, *MonsterAction) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MonsterAttack not implemented")
}
func (UnimplementedPokmonInfoServer) JoinQueue(context.Context, *UserName) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinQueue not implemented")
}
func (UnimplementedPokmonInfoServer) LeaveGame(context.Context, *UserName) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveGame not implemented")
}
func (UnimplementedPokmonInfoServer) SetUserName(context.Context, *UserName) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserName not implemented")
}
func (UnimplementedPokmonInfoServer) GetHealthPoints(context.Context, *HealthRequest) (*HealthPoints, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealthPoints not implemented")
}
func (UnimplementedPokmonInfoServer) GetGameInfo(context.Context, *RequestInfo) (*GameStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGameInfo not implemented")
}
func (UnimplementedPokmonInfoServer) GetOpponentInfo(context.Context, *RequestInfo) (*OpponentStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOpponentInfo not implemented")
}
func (UnimplementedPokmonInfoServer) mustEmbedUnimplementedPokmonInfoServer() {}

// UnsafePokmonInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PokmonInfoServer will
// result in compilation errors.
type UnsafePokmonInfoServer interface {
	mustEmbedUnimplementedPokmonInfoServer()
}

func RegisterPokmonInfoServer(s grpc.ServiceRegistrar, srv PokmonInfoServer) {
	s.RegisterService(&PokmonInfo_ServiceDesc, srv)
}

func _PokmonInfo_GetMonsterInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonsterName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokmonInfoServer).GetMonsterInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokmonapi.PokmonInfo/GetMonsterInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokmonInfoServer).GetMonsterInfo(ctx, req.(*MonsterName))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokmonInfo_SetMonsterInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAndName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokmonInfoServer).SetMonsterInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokmonapi.PokmonInfo/SetMonsterInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokmonInfoServer).SetMonsterInfo(ctx, req.(*UserAndName))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokmonInfo_MonsterAttack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MonsterAction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokmonInfoServer).MonsterAttack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokmonapi.PokmonInfo/MonsterAttack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokmonInfoServer).MonsterAttack(ctx, req.(*MonsterAction))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokmonInfo_JoinQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokmonInfoServer).JoinQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokmonapi.PokmonInfo/JoinQueue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokmonInfoServer).JoinQueue(ctx, req.(*UserName))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokmonInfo_LeaveGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokmonInfoServer).LeaveGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokmonapi.PokmonInfo/LeaveGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokmonInfoServer).LeaveGame(ctx, req.(*UserName))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokmonInfo_SetUserName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokmonInfoServer).SetUserName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokmonapi.PokmonInfo/SetUserName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokmonInfoServer).SetUserName(ctx, req.(*UserName))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokmonInfo_GetHealthPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokmonInfoServer).GetHealthPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokmonapi.PokmonInfo/GetHealthPoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokmonInfoServer).GetHealthPoints(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokmonInfo_GetGameInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokmonInfoServer).GetGameInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokmonapi.PokmonInfo/GetGameInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokmonInfoServer).GetGameInfo(ctx, req.(*RequestInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokmonInfo_GetOpponentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokmonInfoServer).GetOpponentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokmonapi.PokmonInfo/GetOpponentInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokmonInfoServer).GetOpponentInfo(ctx, req.(*RequestInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// PokmonInfo_ServiceDesc is the grpc.ServiceDesc for PokmonInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PokmonInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pokmonapi.PokmonInfo",
	HandlerType: (*PokmonInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMonsterInfo",
			Handler:    _PokmonInfo_GetMonsterInfo_Handler,
		},
		{
			MethodName: "SetMonsterInfo",
			Handler:    _PokmonInfo_SetMonsterInfo_Handler,
		},
		{
			MethodName: "MonsterAttack",
			Handler:    _PokmonInfo_MonsterAttack_Handler,
		},
		{
			MethodName: "JoinQueue",
			Handler:    _PokmonInfo_JoinQueue_Handler,
		},
		{
			MethodName: "LeaveGame",
			Handler:    _PokmonInfo_LeaveGame_Handler,
		},
		{
			MethodName: "SetUserName",
			Handler:    _PokmonInfo_SetUserName_Handler,
		},
		{
			MethodName: "GetHealthPoints",
			Handler:    _PokmonInfo_GetHealthPoints_Handler,
		},
		{
			MethodName: "GetGameInfo",
			Handler:    _PokmonInfo_GetGameInfo_Handler,
		},
		{
			MethodName: "GetOpponentInfo",
			Handler:    _PokmonInfo_GetOpponentInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pokmonapi/pokmonapi.proto",
}
