FROM golang:1.14-alpine AS build

WORKDIR /src/

COPY go.mod /src/
COPY go.sum /src/
RUN go mod download

COPY pokmonapi /src/pokmonapi
COPY gameserver/server.go /src/
RUN CGO_ENABLED=0 go build -o /bin/server

FROM scratch
COPY --from=build /bin/server /bin/server
ENTRYPOINT ["/bin/server"]